//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTHUNHAP
    {
        public int MaTN { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> MaLoaiTN { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<double> SoTienTN { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual LOAITHUNHAP LOAITHUNHAP { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
