//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI
    {
        public int MaPH { get; set; }
        public Nullable<int> ID { get; set; }
        public string TenNguoiDung { get; set; }
        public string LienLac { get; set; }
        public string YKien { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
